# Generated by Django 6.1.1 on 2026-09-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_organizerprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='razorpay_linked_account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
