# Generated by Django 6.1.1 on 2026-09-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_qrs/'),
        ),
    ]
