# Generated by Django 6.1.1 on 2026-09-11 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_ticket_qr_code_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('PAYMENT_SUCCESS', 'Payment Success'), ('TICKET_ISSUED', 'Ticket Issued'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('PAYMENT_FAILED', 'Payment Failed')], max_length=50)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='events.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='events_noti_user_id_cabef2_idx'), models.Index(fields=['notification_type'], name='events_noti_notific_eb43ae_idx')],
            },
        ),
    ]
