# Generated by Django 6.1.1 on 2026-09-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
