# Generated by Django 6.1.1 on 2026-09-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_event_code_eventticketsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
