# Generated by Django 6.1.1 on 2026-09-19 10:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeatConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('REGULAR', 'Regular'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_configurations', to='events.event')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_configurations', to='events.seat')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'seat'), name='unique_event_seat_configuration')],
            },
        ),
    ]
