from django.urls import path

from .views import (
    CategoryCreateView,
    CategoryListView,
    CategorySoftDeleteView,
    CategoryUpdateView,
    EventCreateView,
    EventListView,
    EventDetailView,
    EventStatusView,
    EventUpdateView,
    VenueCreateView,
    VenueListView,
    VenueSoftDeleteView,
    VenueUpdateView,
    ShowListView,
    ShowCreateView,
    ShowUpdateView,
    ShowSoftDeleteView,
    SeatListView,
    SeatCreateView,
    SeatBulkCreateView,
    SeatUpdateView,
    SeatSoftDeleteView,
    WishlistListCreateAPIView,
    WishlistDeleteAPIView,
    BookingCreateView,
    BookingListView,
    BookingDetailView,
    BookingCancelView,
    SeatLockCreateView,
    SeatLockReleaseView,
    ShowAvailableSeatsView,
    PaymentOrderCreateView,
    PaymentVerificationView,
    RazorpayWebhookView,
    TicketDetailView,
    CustomerTicketListView,
    TicketVerificationView,
    TicketCheckInView,
    NotificationListView,
    AdminDashboardStatisticsView,
    AdminEventListView,
    AdminEventDetailView,
    BookingStatusView,
    RazorpayWebhookMockView,
    AdminVenueListView,
    AdminVenueDetailView,
    AdminBookingListView,
    AdminBookingDetailView,
    AdminPaymentListView,
    AdminRevenueReportView,
    AdminTicketReportView,
    AdminEventReportListView,
    OrganizerDashboardStatisticsView,
    OrganizerEventListView,
    OrganizerVenueListView,
    OrganizerBookingListView,
    EventSeatConfigurationBulkAPIView,
    EventSeatConfigurationListAPIView,
)

app_name = "events"

urlpatterns = [
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path(
        "categories/create/",
        CategoryCreateView.as_view(),
        name="category_create",
    ),
    path(
        "categories/<int:pk>/update/",
        CategoryUpdateView.as_view(),
        name="category_update",
    ),
    path(
        "categories/<int:pk>/delete/",
        CategorySoftDeleteView.as_view(),
        name="category_delete",
    ),
    path("venues/", VenueListView.as_view(), name="venue_list"),
    path(
        "venues/create/",
        VenueCreateView.as_view(),
        name="venue_create",
    ),
    path(
        "venues/<int:pk>/update/",
        VenueUpdateView.as_view(),
        name="venue_update",
    ),
    path(
        "venues/<int:pk>/delete/",
        VenueSoftDeleteView.as_view(),
        name="venue_delete",
    ),
    path("events/", EventListView.as_view(), name="event_list"),
    path("events/<int:pk>/", EventDetailView.as_view(), name="event_detail"),
    path("events/create/", EventCreateView.as_view(), name="event_create"),
    path(
        "events/<int:pk>/update/",
        EventUpdateView.as_view(),
        name="event_update",
    ),
    path(
        "events/<int:pk>/status/",
        EventStatusView.as_view(),
        name="event_status",
    ),
    path("shows/", ShowListView.as_view(), name="show_list"),
    path("shows/create/", ShowCreateView.as_view(), name="show_create"),
    path("shows/<int:pk>/update/", ShowUpdateView.as_view(), name="show_update"),
    path("shows/<int:pk>/delete/", ShowSoftDeleteView.as_view(), name="show_delete"),
    path("shows/<int:pk>/available-seats/", ShowAvailableSeatsView.as_view(), name="show_available_seats"),
    path("seats/", SeatListView.as_view(), name="seat_list"),
    path("seats/create/", SeatCreateView.as_view(), name="seat_create"),
    path("seats/bulk-create/", SeatBulkCreateView.as_view(), name="seat_bulk_create"),
    path("seats/<int:pk>/update/", SeatUpdateView.as_view(), name="seat_update"),
    path("seats/<int:pk>/delete/", SeatSoftDeleteView.as_view(), name="seat_delete"),
    path("wishlists/", WishlistListCreateAPIView.as_view(), name="wishlist_create"),
    path("wishlists/<int:pk>/delete/", WishlistDeleteAPIView.as_view(), name="wishlist_delete"),
    path("bookings/", BookingListView.as_view(), name="booking_list"),
    path("bookings/create/", BookingCreateView.as_view(), name="booking_create"),
    path("bookings/<str:booking_reference>/", BookingDetailView.as_view(), name="booking_detail"),
    path("bookings/<str:booking_reference>/cancel/", BookingCancelView.as_view(), name="booking_cancel"),
    path("seat-locks/create/", SeatLockCreateView.as_view(), name="seat_lock_create"),
    path("seat-locks/release/", SeatLockReleaseView.as_view(), name="seat_lock_release"),
    path("payments/create-order/", PaymentOrderCreateView.as_view(), name="payment_create_order"),
    path("payments/verify/", PaymentVerificationView.as_view(), name="payment_verify"),
    path("payments/webhook/", RazorpayWebhookView.as_view(), name="payment_webhook"),
    path("tickets/verify/", TicketVerificationView.as_view(), name="ticket_verify"),
    path("tickets/checkin/", TicketCheckInView.as_view(), name="ticket_checkin"),
    path("notifications/", NotificationListView.as_view(), name="notification_list"),
    path("tickets/my/", CustomerTicketListView.as_view(), name="ticket_my_list"),
    path("tickets/<str:ticket_number>/", TicketDetailView.as_view(), name="ticket_detail"),
    path("bookings/<int:pk>/status/", BookingStatusView.as_view(), name="booking_status"),
    path("payments/mock-webhook/", RazorpayWebhookMockView.as_view(), name="payment_mock_webhook"),
    
    # Organizer
    path("organizer/statistics/", OrganizerDashboardStatisticsView.as_view(), name="organizer_statistics"),
    path("organizer/events/", OrganizerEventListView.as_view(), name="organizer_event_list"),
    path("organizer/venues/", OrganizerVenueListView.as_view(), name="organizer_venue_list"),
    path("organizer/bookings/", OrganizerBookingListView.as_view(), name="organizer_booking_list"),
    path("organizer/events/<int:event_id>/seat-configurations/", EventSeatConfigurationListAPIView.as_view(), name="organizer_seat_configurations"),
    path("organizer/events/<int:event_id>/seat-configurations/bulk/", EventSeatConfigurationBulkAPIView.as_view(), name="organizer_seat_configurations_bulk"),
    
    # Admin
    path("admin/statistics/", AdminDashboardStatisticsView.as_view(), name="admin_statistics"),
    path("admin/events/", AdminEventListView.as_view(), name="admin_event_list"),
    path("admin/events/<int:pk>/", AdminEventDetailView.as_view(), name="admin_event_detail"),
    path("admin/venues/", AdminVenueListView.as_view(), name="admin_venue_list"),
    path("admin/venues/<int:pk>/", AdminVenueDetailView.as_view(), name="admin_venue_detail"),
    path("admin/bookings/", AdminBookingListView.as_view(), name="admin_booking_list"),
    path("admin/bookings/<int:pk>/", AdminBookingDetailView.as_view(), name="admin_booking_detail"),
    path("admin/payments/", AdminPaymentListView.as_view(), name="admin_payment_list"),
    path("admin/revenue/", AdminRevenueReportView.as_view(), name="admin_revenue_report"),
    path("admin/tickets/report/", AdminTicketReportView.as_view(), name="admin_ticket_report"),
    path("admin/events/report/", AdminEventReportListView.as_view(), name="admin_event_report"),
]
